[package]
name = "decdnnf-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.rust]
missing_docs = "warn"

[lints.clippy]
pedantic = "warn"

[dependencies]
anyhow = "1.0"
bitvec = "1.0"
rug = "1.22"